# This is a basic example Blueprint for a Django web service and
# the Render Postgres database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: Proxified-Ports
    runtime: java
    repo: https://github.com/marigaby1980/Proxified-Ports
    buildCommand: "javac"
    startCommand: "Runtime.getRuntime().exec("cmd /c start notepad.exe");"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: thiago-app-db
          property: connectionString

databases:
  - name: thiago-app-db # A Render Postgres database named django-app-db running on a free instance
    plan: free
